apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
data:
  DB_USER: c2E=  # sa en base64
  DB_PASSWORD: WW91clN0cm9uZzFQYXNzdzByZA==  # YourStrong1Passw0rd en base64 